[package]
name = "rusty_chip"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sdl2 = "0.36.0"
clap = { version = "4.5.2", features = ["derive"] }
